from __future__ import annotations

from typing import Any

import pandas as pd

from apps.data_hub.data_pipeline_ts.fetchers.base import BaseFetcher, ColumnDef, TableSchema


class StkFactorProFetch(BaseFetcher):
    """
    API: https://tushare.pro/document/2?doc_id=328
    股票技术面因子(专业版), 5000积分
        获取股票每日技术面因子, 覆盖不复权、前复权、后复权口径。
        已经覆盖日线行情、日线基础指标以及前复权口径的日级字段能力
    API params:
        ts_code: 股票代码
        trade_date: 交易日期(YYYYMMDD)
        start_date: 开始日期
        end_date: 结束日期
    """

    fields = [
        "ts_code",
        "trade_date",
        "open",
        "open_hfq",
        "open_qfq",
        "high",
        "high_hfq",
        "high_qfq",
        "low",
        "low_hfq",
        "low_qfq",
        "close",
        "close_hfq",
        "close_qfq",
        "pre_close",
        "change",
        "pct_chg",
        "vol",
        "amount",
        "turnover_rate",
        "turnover_rate_f",
        "volume_ratio",
        "pe",
        "pe_ttm",
        "pb",
        "ps",
        "ps_ttm",
        "dv_ratio",
        "dv_ttm",
        "total_share",
        "float_share",
        "free_share",
        "total_mv",
        "circ_mv",
        "adj_factor",
        "asi_bfq",
        "asi_hfq",
        "asi_qfq",
        "asit_bfq",
        "asit_hfq",
        "asit_qfq",
        "atr_bfq",
        "atr_hfq",
        "atr_qfq",
        "bbi_bfq",
        "bbi_hfq",
        "bbi_qfq",
        "bias1_bfq",
        "bias1_hfq",
        "bias1_qfq",
        "bias2_bfq",
        "bias2_hfq",
        "bias2_qfq",
        "bias3_bfq",
        "bias3_hfq",
        "bias3_qfq",
        "boll_lower_bfq",
        "boll_lower_hfq",
        "boll_lower_qfq",
        "boll_mid_bfq",
        "boll_mid_hfq",
        "boll_mid_qfq",
        "boll_upper_bfq",
        "boll_upper_hfq",
        "boll_upper_qfq",
        "brar_ar_bfq",
        "brar_ar_hfq",
        "brar_ar_qfq",
        "brar_br_bfq",
        "brar_br_hfq",
        "brar_br_qfq",
        "cci_bfq",
        "cci_hfq",
        "cci_qfq",
        "cr_bfq",
        "cr_hfq",
        "cr_qfq",
        "dfma_dif_bfq",
        "dfma_dif_hfq",
        "dfma_dif_qfq",
        "dfma_difma_bfq",
        "dfma_difma_hfq",
        "dfma_difma_qfq",
        "dmi_adx_bfq",
        "dmi_adx_hfq",
        "dmi_adx_qfq",
        "dmi_adxr_bfq",
        "dmi_adxr_hfq",
        "dmi_adxr_qfq",
        "dmi_mdi_bfq",
        "dmi_mdi_hfq",
        "dmi_mdi_qfq",
        "dmi_pdi_bfq",
        "dmi_pdi_hfq",
        "dmi_pdi_qfq",
        "downdays",
        "updays",
        "dpo_bfq",
        "dpo_hfq",
        "dpo_qfq",
        "madpo_bfq",
        "madpo_hfq",
        "madpo_qfq",
        "ema_bfq_10",
        "ema_bfq_20",
        "ema_bfq_250",
        "ema_bfq_30",
        "ema_bfq_5",
        "ema_bfq_60",
        "ema_bfq_90",
        "ema_hfq_10",
        "ema_hfq_20",
        "ema_hfq_250",
        "ema_hfq_30",
        "ema_hfq_5",
        "ema_hfq_60",
        "ema_hfq_90",
        "ema_qfq_10",
        "ema_qfq_20",
        "ema_qfq_250",
        "ema_qfq_30",
        "ema_qfq_5",
        "ema_qfq_60",
        "ema_qfq_90",
        "emv_bfq",
        "emv_hfq",
        "emv_qfq",
        "maemv_bfq",
        "maemv_hfq",
        "maemv_qfq",
        "expma_12_bfq",
        "expma_12_hfq",
        "expma_12_qfq",
        "expma_50_bfq",
        "expma_50_hfq",
        "expma_50_qfq",
        "kdj_bfq",
        "kdj_hfq",
        "kdj_qfq",
        "kdj_d_bfq",
        "kdj_d_hfq",
        "kdj_d_qfq",
        "kdj_k_bfq",
        "kdj_k_hfq",
        "kdj_k_qfq",
        "ktn_down_bfq",
        "ktn_down_hfq",
        "ktn_down_qfq",
        "ktn_mid_bfq",
        "ktn_mid_hfq",
        "ktn_mid_qfq",
        "ktn_upper_bfq",
        "ktn_upper_hfq",
        "ktn_upper_qfq",
        "lowdays",
        "topdays",
        "ma_bfq_10",
        "ma_bfq_20",
        "ma_bfq_250",
        "ma_bfq_30",
        "ma_bfq_5",
        "ma_bfq_60",
        "ma_bfq_90",
        "ma_hfq_10",
        "ma_hfq_20",
        "ma_hfq_250",
        "ma_hfq_30",
        "ma_hfq_5",
        "ma_hfq_60",
        "ma_hfq_90",
        "ma_qfq_10",
        "ma_qfq_20",
        "ma_qfq_250",
        "ma_qfq_30",
        "ma_qfq_5",
        "ma_qfq_60",
        "ma_qfq_90",
        "macd_bfq",
        "macd_hfq",
        "macd_qfq",
        "macd_dea_bfq",
        "macd_dea_hfq",
        "macd_dea_qfq",
        "macd_dif_bfq",
        "macd_dif_hfq",
        "macd_dif_qfq",
        "mass_bfq",
        "mass_hfq",
        "mass_qfq",
        "ma_mass_bfq",
        "ma_mass_hfq",
        "ma_mass_qfq",
        "mfi_bfq",
        "mfi_hfq",
        "mfi_qfq",
        "mtm_bfq",
        "mtm_hfq",
        "mtm_qfq",
        "mtmma_bfq",
        "mtmma_hfq",
        "mtmma_qfq",
        "obv_bfq",
        "obv_hfq",
        "obv_qfq",
        "psy_bfq",
        "psy_hfq",
        "psy_qfq",
        "psyma_bfq",
        "psyma_hfq",
        "psyma_qfq",
        "roc_bfq",
        "roc_hfq",
        "roc_qfq",
        "maroc_bfq",
        "maroc_hfq",
        "maroc_qfq",
        "rsi_bfq_12",
        "rsi_bfq_24",
        "rsi_bfq_6",
        "rsi_hfq_12",
        "rsi_hfq_24",
        "rsi_hfq_6",
        "rsi_qfq_12",
        "rsi_qfq_24",
        "rsi_qfq_6",
        "taq_down_bfq",
        "taq_down_hfq",
        "taq_down_qfq",
        "taq_mid_bfq",
        "taq_mid_hfq",
        "taq_mid_qfq",
        "taq_up_bfq",
        "taq_up_hfq",
        "taq_up_qfq",
        "trix_bfq",
        "trix_hfq",
        "trix_qfq",
        "trma_bfq",
        "trma_hfq",
        "trma_qfq",
        "vr_bfq",
        "vr_hfq",
        "vr_qfq",
        "wr_bfq",
        "wr_hfq",
        "wr_qfq",
        "wr1_bfq",
        "wr1_hfq",
        "wr1_qfq",
        "xsii_td1_bfq",
        "xsii_td1_hfq",
        "xsii_td1_qfq",
        "xsii_td2_bfq",
        "xsii_td2_hfq",
        "xsii_td2_qfq",
        "xsii_td3_bfq",
        "xsii_td3_hfq",
        "xsii_td3_qfq",
        "xsii_td4_bfq",
        "xsii_td4_hfq",
        "xsii_td4_qfq",
    ]
    table_schema = TableSchema(
        columns={
            "ts_code": ColumnDef("VARCHAR(16)", nullable=True, comment="股票代码"),
            "trade_date": ColumnDef("CHAR(8)", nullable=True, comment="交易日期"),
            "open": ColumnDef("DOUBLE", nullable=True, comment="开盘价"),
            "open_hfq": ColumnDef("DOUBLE", nullable=True, comment="开盘价(后复权)"),
            "open_qfq": ColumnDef("DOUBLE", nullable=True, comment="开盘价(前复权)"),
            "high": ColumnDef("DOUBLE", nullable=True, comment="最高价"),
            "high_hfq": ColumnDef("DOUBLE", nullable=True, comment="最高价(后复权)"),
            "high_qfq": ColumnDef("DOUBLE", nullable=True, comment="最高价(前复权)"),
            "low": ColumnDef("DOUBLE", nullable=True, comment="最低价"),
            "low_hfq": ColumnDef("DOUBLE", nullable=True, comment="最低价(后复权)"),
            "low_qfq": ColumnDef("DOUBLE", nullable=True, comment="最低价(前复权)"),
            "close": ColumnDef("DOUBLE", nullable=True, comment="收盘价"),
            "close_hfq": ColumnDef("DOUBLE", nullable=True, comment="收盘价(后复权)"),
            "close_qfq": ColumnDef("DOUBLE", nullable=True, comment="收盘价(前复权)"),
            "pre_close": ColumnDef(
                "DOUBLE",
                nullable=True,
                comment="昨收价(前复权)--为daily接口的pre_close,以当时复权因子计算值跟前一日close_qfq对不上, 可不用",
            ),
            "change": ColumnDef("DOUBLE", nullable=True, comment="涨跌额"),
            "pct_chg": ColumnDef("DOUBLE", nullable=True, comment="涨跌幅(除权后的涨跌幅)"),
            "vol": ColumnDef("DOUBLE", nullable=True, comment="成交量(手)"),
            "amount": ColumnDef("DOUBLE", nullable=True, comment="成交额(千元)"),
            "turnover_rate": ColumnDef("DOUBLE", nullable=True, comment="换手率(%)"),
            "turnover_rate_f": ColumnDef("DOUBLE", nullable=True, comment="换手率(自由流通股)"),
            "volume_ratio": ColumnDef("DOUBLE", nullable=True, comment="量比"),
            "pe": ColumnDef("DOUBLE", nullable=True, comment="市盈率(总市值/净利润,  亏损的PE为空)"),
            "pe_ttm": ColumnDef("DOUBLE", nullable=True, comment="市盈率(TTM, 亏损的PE为空)"),
            "pb": ColumnDef("DOUBLE", nullable=True, comment="市净率(总市值/净资产)"),
            "ps": ColumnDef("DOUBLE", nullable=True, comment="市销率"),
            "ps_ttm": ColumnDef("DOUBLE", nullable=True, comment="市销率(TTM)"),
            "dv_ratio": ColumnDef("DOUBLE", nullable=True, comment="股息率(%)"),
            "dv_ttm": ColumnDef("DOUBLE", nullable=True, comment="股息率(TTM)(%)"),
            "total_share": ColumnDef("DOUBLE", nullable=True, comment="总股本(万股)"),
            "float_share": ColumnDef("DOUBLE", nullable=True, comment="流通股本(万股)"),
            "free_share": ColumnDef("DOUBLE", nullable=True, comment="自由流通股本(万)"),
            "total_mv": ColumnDef("DOUBLE", nullable=True, comment="总市值(万元)"),
            "circ_mv": ColumnDef("DOUBLE", nullable=True, comment="流通市值(万元)"),
            "adj_factor": ColumnDef("DOUBLE", nullable=True, comment="复权因子"),
            "asi_bfq": ColumnDef("DOUBLE", nullable=True, comment="振动升降指标-OPEN, CLOSE, HIGH, LOW, M1=26, M2=10"),
            "asi_hfq": ColumnDef("DOUBLE", nullable=True, comment="振动升降指标-OPEN, CLOSE, HIGH, LOW, M1=26, M2=10"),
            "asi_qfq": ColumnDef("DOUBLE", nullable=True, comment="振动升降指标-OPEN, CLOSE, HIGH, LOW, M1=26, M2=10"),
            "asit_bfq": ColumnDef("DOUBLE", nullable=True, comment="振动升降指标-OPEN, CLOSE, HIGH, LOW, M1=26, M2=10"),
            "asit_hfq": ColumnDef("DOUBLE", nullable=True, comment="振动升降指标-OPEN, CLOSE, HIGH, LOW, M1=26, M2=10"),
            "asit_qfq": ColumnDef("DOUBLE", nullable=True, comment="振动升降指标-OPEN, CLOSE, HIGH, LOW, M1=26, M2=10"),
            "atr_bfq": ColumnDef("DOUBLE", nullable=True, comment="真实波动N日平均值-CLOSE, HIGH, LOW, N=20"),
            "atr_hfq": ColumnDef("DOUBLE", nullable=True, comment="真实波动N日平均值-CLOSE, HIGH, LOW, N=20"),
            "atr_qfq": ColumnDef("DOUBLE", nullable=True, comment="真实波动N日平均值-CLOSE, HIGH, LOW, N=20"),
            "bbi_bfq": ColumnDef("DOUBLE", nullable=True, comment="BBI多空指标-CLOSE, M1=3, M2=6, M3=12, M4=20"),
            "bbi_hfq": ColumnDef("DOUBLE", nullable=True, comment="BBI多空指标-CLOSE, M1=3, M2=6, M3=12, M4=21"),
            "bbi_qfq": ColumnDef("DOUBLE", nullable=True, comment="BBI多空指标-CLOSE, M1=3, M2=6, M3=12, M4=22"),
            "bias1_bfq": ColumnDef("DOUBLE", nullable=True, comment="BIAS乖离率-CLOSE, L1=6, L2=12, L3=24"),
            "bias1_hfq": ColumnDef("DOUBLE", nullable=True, comment="BIAS乖离率-CLOSE, L1=6, L2=12, L3=24"),
            "bias1_qfq": ColumnDef("DOUBLE", nullable=True, comment="BIAS乖离率-CLOSE, L1=6, L2=12, L3=24"),
            "bias2_bfq": ColumnDef("DOUBLE", nullable=True, comment="BIAS乖离率-CLOSE, L1=6, L2=12, L3=24"),
            "bias2_hfq": ColumnDef("DOUBLE", nullable=True, comment="BIAS乖离率-CLOSE, L1=6, L2=12, L3=24"),
            "bias2_qfq": ColumnDef("DOUBLE", nullable=True, comment="BIAS乖离率-CLOSE, L1=6, L2=12, L3=24"),
            "bias3_bfq": ColumnDef("DOUBLE", nullable=True, comment="BIAS乖离率-CLOSE, L1=6, L2=12, L3=24"),
            "bias3_hfq": ColumnDef("DOUBLE", nullable=True, comment="BIAS乖离率-CLOSE, L1=6, L2=12, L3=24"),
            "bias3_qfq": ColumnDef("DOUBLE", nullable=True, comment="BIAS乖离率-CLOSE, L1=6, L2=12, L3=24"),
            "boll_lower_bfq": ColumnDef("DOUBLE", nullable=True, comment="BOLL指标, 布林带-CLOSE, N=20, P=2"),
            "boll_lower_hfq": ColumnDef("DOUBLE", nullable=True, comment="BOLL指标, 布林带-CLOSE, N=20, P=2"),
            "boll_lower_qfq": ColumnDef("DOUBLE", nullable=True, comment="BOLL指标, 布林带-CLOSE, N=20, P=2"),
            "boll_mid_bfq": ColumnDef("DOUBLE", nullable=True, comment="BOLL指标, 布林带-CLOSE, N=20, P=2"),
            "boll_mid_hfq": ColumnDef("DOUBLE", nullable=True, comment="BOLL指标, 布林带-CLOSE, N=20, P=2"),
            "boll_mid_qfq": ColumnDef("DOUBLE", nullable=True, comment="BOLL指标, 布林带-CLOSE, N=20, P=2"),
            "boll_upper_bfq": ColumnDef("DOUBLE", nullable=True, comment="BOLL指标, 布林带-CLOSE, N=20, P=2"),
            "boll_upper_hfq": ColumnDef("DOUBLE", nullable=True, comment="BOLL指标, 布林带-CLOSE, N=20, P=2"),
            "boll_upper_qfq": ColumnDef("DOUBLE", nullable=True, comment="BOLL指标, 布林带-CLOSE, N=20, P=2"),
            "brar_ar_bfq": ColumnDef("DOUBLE", nullable=True, comment="BRAR情绪指标-OPEN, CLOSE, HIGH, LOW, M1=26"),
            "brar_ar_hfq": ColumnDef("DOUBLE", nullable=True, comment="BRAR情绪指标-OPEN, CLOSE, HIGH, LOW, M1=26"),
            "brar_ar_qfq": ColumnDef("DOUBLE", nullable=True, comment="BRAR情绪指标-OPEN, CLOSE, HIGH, LOW, M1=26"),
            "brar_br_bfq": ColumnDef("DOUBLE", nullable=True, comment="BRAR情绪指标-OPEN, CLOSE, HIGH, LOW, M1=26"),
            "brar_br_hfq": ColumnDef("DOUBLE", nullable=True, comment="BRAR情绪指标-OPEN, CLOSE, HIGH, LOW, M1=26"),
            "brar_br_qfq": ColumnDef("DOUBLE", nullable=True, comment="BRAR情绪指标-OPEN, CLOSE, HIGH, LOW, M1=26"),
            "cci_bfq": ColumnDef("DOUBLE", nullable=True, comment="顺势指标又叫CCI指标-CLOSE, HIGH, LOW, N=14"),
            "cci_hfq": ColumnDef("DOUBLE", nullable=True, comment="顺势指标又叫CCI指标-CLOSE, HIGH, LOW, N=14"),
            "cci_qfq": ColumnDef("DOUBLE", nullable=True, comment="顺势指标又叫CCI指标-CLOSE, HIGH, LOW, N=14"),
            "cr_bfq": ColumnDef("DOUBLE", nullable=True, comment="CR价格动量指标-CLOSE, HIGH, LOW, N=20"),
            "cr_hfq": ColumnDef("DOUBLE", nullable=True, comment="CR价格动量指标-CLOSE, HIGH, LOW, N=20"),
            "cr_qfq": ColumnDef("DOUBLE", nullable=True, comment="CR价格动量指标-CLOSE, HIGH, LOW, N=20"),
            "dfma_dif_bfq": ColumnDef("DOUBLE", nullable=True, comment="平行线差指标-CLOSE, N1=10, N2=50, M=10"),
            "dfma_dif_hfq": ColumnDef("DOUBLE", nullable=True, comment="平行线差指标-CLOSE, N1=10, N2=50, M=10"),
            "dfma_dif_qfq": ColumnDef("DOUBLE", nullable=True, comment="平行线差指标-CLOSE, N1=10, N2=50, M=10"),
            "dfma_difma_bfq": ColumnDef("DOUBLE", nullable=True, comment="平行线差指标-CLOSE, N1=10, N2=50, M=10"),
            "dfma_difma_hfq": ColumnDef("DOUBLE", nullable=True, comment="平行线差指标-CLOSE, N1=10, N2=50, M=10"),
            "dfma_difma_qfq": ColumnDef("DOUBLE", nullable=True, comment="平行线差指标-CLOSE, N1=10, N2=50, M=10"),
            "dmi_adx_bfq": ColumnDef("DOUBLE", nullable=True, comment="动向指标-CLOSE, HIGH, LOW, M1=14, M2=6"),
            "dmi_adx_hfq": ColumnDef("DOUBLE", nullable=True, comment="动向指标-CLOSE, HIGH, LOW, M1=14, M2=6"),
            "dmi_adx_qfq": ColumnDef("DOUBLE", nullable=True, comment="动向指标-CLOSE, HIGH, LOW, M1=14, M2=6"),
            "dmi_adxr_bfq": ColumnDef("DOUBLE", nullable=True, comment="动向指标-CLOSE, HIGH, LOW, M1=14, M2=6"),
            "dmi_adxr_hfq": ColumnDef("DOUBLE", nullable=True, comment="动向指标-CLOSE, HIGH, LOW, M1=14, M2=6"),
            "dmi_adxr_qfq": ColumnDef("DOUBLE", nullable=True, comment="动向指标-CLOSE, HIGH, LOW, M1=14, M2=6"),
            "dmi_mdi_bfq": ColumnDef("DOUBLE", nullable=True, comment="动向指标-CLOSE, HIGH, LOW, M1=14, M2=6"),
            "dmi_mdi_hfq": ColumnDef("DOUBLE", nullable=True, comment="动向指标-CLOSE, HIGH, LOW, M1=14, M2=6"),
            "dmi_mdi_qfq": ColumnDef("DOUBLE", nullable=True, comment="动向指标-CLOSE, HIGH, LOW, M1=14, M2=6"),
            "dmi_pdi_bfq": ColumnDef("DOUBLE", nullable=True, comment="动向指标-CLOSE, HIGH, LOW, M1=14, M2=6"),
            "dmi_pdi_hfq": ColumnDef("DOUBLE", nullable=True, comment="动向指标-CLOSE, HIGH, LOW, M1=14, M2=6"),
            "dmi_pdi_qfq": ColumnDef("DOUBLE", nullable=True, comment="动向指标-CLOSE, HIGH, LOW, M1=14, M2=6"),
            "downdays": ColumnDef("DOUBLE", nullable=True, comment="连跌天数"),
            "updays": ColumnDef("DOUBLE", nullable=True, comment="连涨天数"),
            "dpo_bfq": ColumnDef("DOUBLE", nullable=True, comment="区间震荡线-CLOSE, M1=20, M2=10, M3=6"),
            "dpo_hfq": ColumnDef("DOUBLE", nullable=True, comment="区间震荡线-CLOSE, M1=20, M2=10, M3=6"),
            "dpo_qfq": ColumnDef("DOUBLE", nullable=True, comment="区间震荡线-CLOSE, M1=20, M2=10, M3=6"),
            "madpo_bfq": ColumnDef("DOUBLE", nullable=True, comment="区间震荡线-CLOSE, M1=20, M2=10, M3=6"),
            "madpo_hfq": ColumnDef("DOUBLE", nullable=True, comment="区间震荡线-CLOSE, M1=20, M2=10, M3=6"),
            "madpo_qfq": ColumnDef("DOUBLE", nullable=True, comment="区间震荡线-CLOSE, M1=20, M2=10, M3=6"),
            "ema_bfq_10": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=10"),
            "ema_bfq_20": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=20"),
            "ema_bfq_250": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=250"),
            "ema_bfq_30": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=30"),
            "ema_bfq_5": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=5"),
            "ema_bfq_60": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=60"),
            "ema_bfq_90": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=90"),
            "ema_hfq_10": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=10"),
            "ema_hfq_20": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=20"),
            "ema_hfq_250": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=250"),
            "ema_hfq_30": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=30"),
            "ema_hfq_5": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=5"),
            "ema_hfq_60": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=60"),
            "ema_hfq_90": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=90"),
            "ema_qfq_10": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=10"),
            "ema_qfq_20": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=20"),
            "ema_qfq_250": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=250"),
            "ema_qfq_30": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=30"),
            "ema_qfq_5": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=5"),
            "ema_qfq_60": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=60"),
            "ema_qfq_90": ColumnDef("DOUBLE", nullable=True, comment="指数移动平均-N=90"),
            "emv_bfq": ColumnDef("DOUBLE", nullable=True, comment="简易波动指标-HIGH, LOW, VOL, N=14, M=9"),
            "emv_hfq": ColumnDef("DOUBLE", nullable=True, comment="简易波动指标-HIGH, LOW, VOL, N=14, M=9"),
            "emv_qfq": ColumnDef("DOUBLE", nullable=True, comment="简易波动指标-HIGH, LOW, VOL, N=14, M=9"),
            "maemv_bfq": ColumnDef("DOUBLE", nullable=True, comment="简易波动指标-HIGH, LOW, VOL, N=14, M=9"),
            "maemv_hfq": ColumnDef("DOUBLE", nullable=True, comment="简易波动指标-HIGH, LOW, VOL, N=14, M=9"),
            "maemv_qfq": ColumnDef("DOUBLE", nullable=True, comment="简易波动指标-HIGH, LOW, VOL, N=14, M=9"),
            "expma_12_bfq": ColumnDef("DOUBLE", nullable=True, comment="EMA指数平均数指标-CLOSE, N1=12, N2=50"),
            "expma_12_hfq": ColumnDef("DOUBLE", nullable=True, comment="EMA指数平均数指标-CLOSE, N1=12, N2=50"),
            "expma_12_qfq": ColumnDef("DOUBLE", nullable=True, comment="EMA指数平均数指标-CLOSE, N1=12, N2=50"),
            "expma_50_bfq": ColumnDef("DOUBLE", nullable=True, comment="EMA指数平均数指标-CLOSE, N1=12, N2=50"),
            "expma_50_hfq": ColumnDef("DOUBLE", nullable=True, comment="EMA指数平均数指标-CLOSE, N1=12, N2=50"),
            "expma_50_qfq": ColumnDef("DOUBLE", nullable=True, comment="EMA指数平均数指标-CLOSE, N1=12, N2=50"),
            "kdj_bfq": ColumnDef("DOUBLE", nullable=True, comment="KDJ指标-CLOSE, HIGH, LOW, N=9, M1=3, M2=3"),
            "kdj_hfq": ColumnDef("DOUBLE", nullable=True, comment="KDJ指标-CLOSE, HIGH, LOW, N=9, M1=3, M2=3"),
            "kdj_qfq": ColumnDef("DOUBLE", nullable=True, comment="KDJ指标-CLOSE, HIGH, LOW, N=9, M1=3, M2=3"),
            "kdj_d_bfq": ColumnDef("DOUBLE", nullable=True, comment="KDJ指标-CLOSE, HIGH, LOW, N=9, M1=3, M2=3"),
            "kdj_d_hfq": ColumnDef("DOUBLE", nullable=True, comment="KDJ指标-CLOSE, HIGH, LOW, N=9, M1=3, M2=3"),
            "kdj_d_qfq": ColumnDef("DOUBLE", nullable=True, comment="KDJ指标-CLOSE, HIGH, LOW, N=9, M1=3, M2=3"),
            "kdj_k_bfq": ColumnDef("DOUBLE", nullable=True, comment="KDJ指标-CLOSE, HIGH, LOW, N=9, M1=3, M2=3"),
            "kdj_k_hfq": ColumnDef("DOUBLE", nullable=True, comment="KDJ指标-CLOSE, HIGH, LOW, N=9, M1=3, M2=3"),
            "kdj_k_qfq": ColumnDef("DOUBLE", nullable=True, comment="KDJ指标-CLOSE, HIGH, LOW, N=9, M1=3, M2=3"),
            "ktn_down_bfq": ColumnDef("DOUBLE", nullable=True, comment="肯特纳交易通道, N选20日, ATR选10日-CLOSE, HIGH, LOW, N=20, M=10"),
            "ktn_down_hfq": ColumnDef("DOUBLE", nullable=True, comment="肯特纳交易通道, N选20日, ATR选10日-CLOSE, HIGH, LOW, N=20, M=10"),
            "ktn_down_qfq": ColumnDef("DOUBLE", nullable=True, comment="肯特纳交易通道, N选20日, ATR选10日-CLOSE, HIGH, LOW, N=20, M=10"),
            "ktn_mid_bfq": ColumnDef("DOUBLE", nullable=True, comment="肯特纳交易通道, N选20日, ATR选10日-CLOSE, HIGH, LOW, N=20, M=10"),
            "ktn_mid_hfq": ColumnDef("DOUBLE", nullable=True, comment="肯特纳交易通道, N选20日, ATR选10日-CLOSE, HIGH, LOW, N=20, M=10"),
            "ktn_mid_qfq": ColumnDef("DOUBLE", nullable=True, comment="肯特纳交易通道, N选20日, ATR选10日-CLOSE, HIGH, LOW, N=20, M=10"),
            "ktn_upper_bfq": ColumnDef("DOUBLE", nullable=True, comment="肯特纳交易通道, N选20日, ATR选10日-CLOSE, HIGH, LOW, N=20, M=10"),
            "ktn_upper_hfq": ColumnDef("DOUBLE", nullable=True, comment="肯特纳交易通道, N选20日, ATR选10日-CLOSE, HIGH, LOW, N=20, M=10"),
            "ktn_upper_qfq": ColumnDef("DOUBLE", nullable=True, comment="肯特纳交易通道, N选20日, ATR选10日-CLOSE, HIGH, LOW, N=20, M=10"),
            "lowdays": ColumnDef("DOUBLE", nullable=True, comment="LOWRANGE(LOW)表示当前最低价是近多少周期内最低价的最小值"),
            "topdays": ColumnDef("DOUBLE", nullable=True, comment="TOPRANGE(HIGH)表示当前最高价是近多少周期内最高价的最大值"),
            "ma_bfq_10": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=10"),
            "ma_bfq_20": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=20"),
            "ma_bfq_250": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=250"),
            "ma_bfq_30": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=30"),
            "ma_bfq_5": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=5"),
            "ma_bfq_60": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=60"),
            "ma_bfq_90": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=90"),
            "ma_hfq_10": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=10"),
            "ma_hfq_20": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=20"),
            "ma_hfq_250": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=250"),
            "ma_hfq_30": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=30"),
            "ma_hfq_5": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=5"),
            "ma_hfq_60": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=60"),
            "ma_hfq_90": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=90"),
            "ma_qfq_10": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=10"),
            "ma_qfq_20": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=20"),
            "ma_qfq_250": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=250"),
            "ma_qfq_30": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=30"),
            "ma_qfq_5": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=5"),
            "ma_qfq_60": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=60"),
            "ma_qfq_90": ColumnDef("DOUBLE", nullable=True, comment="简单移动平均-N=90"),
            "macd_bfq": ColumnDef("DOUBLE", nullable=True, comment="MACD指标-CLOSE, SHORT=12, LONG=26, M=9"),
            "macd_hfq": ColumnDef("DOUBLE", nullable=True, comment="MACD指标-CLOSE, SHORT=12, LONG=26, M=9"),
            "macd_qfq": ColumnDef("DOUBLE", nullable=True, comment="MACD指标-CLOSE, SHORT=12, LONG=26, M=9"),
            "macd_dea_bfq": ColumnDef("DOUBLE", nullable=True, comment="MACD指标-CLOSE, SHORT=12, LONG=26, M=9"),
            "macd_dea_hfq": ColumnDef("DOUBLE", nullable=True, comment="MACD指标-CLOSE, SHORT=12, LONG=26, M=9"),
            "macd_dea_qfq": ColumnDef("DOUBLE", nullable=True, comment="MACD指标-CLOSE, SHORT=12, LONG=26, M=9"),
            "macd_dif_bfq": ColumnDef("DOUBLE", nullable=True, comment="MACD指标-CLOSE, SHORT=12, LONG=26, M=9"),
            "macd_dif_hfq": ColumnDef("DOUBLE", nullable=True, comment="MACD指标-CLOSE, SHORT=12, LONG=26, M=9"),
            "macd_dif_qfq": ColumnDef("DOUBLE", nullable=True, comment="MACD指标-CLOSE, SHORT=12, LONG=26, M=9"),
            "mass_bfq": ColumnDef("DOUBLE", nullable=True, comment="梅斯线-HIGH, LOW, N1=9, N2=25, M=6"),
            "mass_hfq": ColumnDef("DOUBLE", nullable=True, comment="梅斯线-HIGH, LOW, N1=9, N2=25, M=6"),
            "mass_qfq": ColumnDef("DOUBLE", nullable=True, comment="梅斯线-HIGH, LOW, N1=9, N2=25, M=6"),
            "ma_mass_bfq": ColumnDef("DOUBLE", nullable=True, comment="梅斯线-HIGH, LOW, N1=9, N2=25, M=6"),
            "ma_mass_hfq": ColumnDef("DOUBLE", nullable=True, comment="梅斯线-HIGH, LOW, N1=9, N2=25, M=6"),
            "ma_mass_qfq": ColumnDef("DOUBLE", nullable=True, comment="梅斯线-HIGH, LOW, N1=9, N2=25, M=6"),
            "mfi_bfq": ColumnDef("DOUBLE", nullable=True, comment="MFI指标是成交量的RSI指标-CLOSE, HIGH, LOW, VOL, N=14"),
            "mfi_hfq": ColumnDef("DOUBLE", nullable=True, comment="MFI指标是成交量的RSI指标-CLOSE, HIGH, LOW, VOL, N=14"),
            "mfi_qfq": ColumnDef("DOUBLE", nullable=True, comment="MFI指标是成交量的RSI指标-CLOSE, HIGH, LOW, VOL, N=14"),
            "mtm_bfq": ColumnDef("DOUBLE", nullable=True, comment="动量指标-CLOSE, N=12, M=6"),
            "mtm_hfq": ColumnDef("DOUBLE", nullable=True, comment="动量指标-CLOSE, N=12, M=6"),
            "mtm_qfq": ColumnDef("DOUBLE", nullable=True, comment="动量指标-CLOSE, N=12, M=6"),
            "mtmma_bfq": ColumnDef("DOUBLE", nullable=True, comment="动量指标-CLOSE, N=12, M=6"),
            "mtmma_hfq": ColumnDef("DOUBLE", nullable=True, comment="动量指标-CLOSE, N=12, M=6"),
            "mtmma_qfq": ColumnDef("DOUBLE", nullable=True, comment="动量指标-CLOSE, N=12, M=6"),
            "obv_bfq": ColumnDef("DOUBLE", nullable=True, comment="能量潮指标-CLOSE, VOL"),
            "obv_hfq": ColumnDef("DOUBLE", nullable=True, comment="能量潮指标-CLOSE, VOL"),
            "obv_qfq": ColumnDef("DOUBLE", nullable=True, comment="能量潮指标-CLOSE, VOL"),
            "psy_bfq": ColumnDef("DOUBLE", nullable=True, comment="投资者对股市涨跌产生心理波动的情绪指标-CLOSE, N=12, M=6"),
            "psy_hfq": ColumnDef("DOUBLE", nullable=True, comment="投资者对股市涨跌产生心理波动的情绪指标-CLOSE, N=12, M=6"),
            "psy_qfq": ColumnDef("DOUBLE", nullable=True, comment="投资者对股市涨跌产生心理波动的情绪指标-CLOSE, N=12, M=6"),
            "psyma_bfq": ColumnDef("DOUBLE", nullable=True, comment="投资者对股市涨跌产生心理波动的情绪指标-CLOSE, N=12, M=6"),
            "psyma_hfq": ColumnDef("DOUBLE", nullable=True, comment="投资者对股市涨跌产生心理波动的情绪指标-CLOSE, N=12, M=6"),
            "psyma_qfq": ColumnDef("DOUBLE", nullable=True, comment="投资者对股市涨跌产生心理波动的情绪指标-CLOSE, N=12, M=6"),
            "roc_bfq": ColumnDef("DOUBLE", nullable=True, comment="变动率指标-CLOSE, N=12, M=6"),
            "roc_hfq": ColumnDef("DOUBLE", nullable=True, comment="变动率指标-CLOSE, N=12, M=6"),
            "roc_qfq": ColumnDef("DOUBLE", nullable=True, comment="变动率指标-CLOSE, N=12, M=6"),
            "maroc_bfq": ColumnDef("DOUBLE", nullable=True, comment="变动率指标-CLOSE, N=12, M=6"),
            "maroc_hfq": ColumnDef("DOUBLE", nullable=True, comment="变动率指标-CLOSE, N=12, M=6"),
            "maroc_qfq": ColumnDef("DOUBLE", nullable=True, comment="变动率指标-CLOSE, N=12, M=6"),
            "rsi_bfq_12": ColumnDef("DOUBLE", nullable=True, comment="RSI指标-CLOSE, N=12"),
            "rsi_bfq_24": ColumnDef("DOUBLE", nullable=True, comment="RSI指标-CLOSE, N=24"),
            "rsi_bfq_6": ColumnDef("DOUBLE", nullable=True, comment="RSI指标-CLOSE, N=6"),
            "rsi_hfq_12": ColumnDef("DOUBLE", nullable=True, comment="RSI指标-CLOSE, N=12"),
            "rsi_hfq_24": ColumnDef("DOUBLE", nullable=True, comment="RSI指标-CLOSE, N=24"),
            "rsi_hfq_6": ColumnDef("DOUBLE", nullable=True, comment="RSI指标-CLOSE, N=6"),
            "rsi_qfq_12": ColumnDef("DOUBLE", nullable=True, comment="RSI指标-CLOSE, N=12"),
            "rsi_qfq_24": ColumnDef("DOUBLE", nullable=True, comment="RSI指标-CLOSE, N=24"),
            "rsi_qfq_6": ColumnDef("DOUBLE", nullable=True, comment="RSI指标-CLOSE, N=6"),
            "taq_down_bfq": ColumnDef("DOUBLE", nullable=True, comment="唐安奇通道(海龟)交易指标-HIGH, LOW, 20"),
            "taq_down_hfq": ColumnDef("DOUBLE", nullable=True, comment="唐安奇通道(海龟)交易指标-HIGH, LOW, 20"),
            "taq_down_qfq": ColumnDef("DOUBLE", nullable=True, comment="唐安奇通道(海龟)交易指标-HIGH, LOW, 20"),
            "taq_mid_bfq": ColumnDef("DOUBLE", nullable=True, comment="唐安奇通道(海龟)交易指标-HIGH, LOW, 20"),
            "taq_mid_hfq": ColumnDef("DOUBLE", nullable=True, comment="唐安奇通道(海龟)交易指标-HIGH, LOW, 20"),
            "taq_mid_qfq": ColumnDef("DOUBLE", nullable=True, comment="唐安奇通道(海龟)交易指标-HIGH, LOW, 20"),
            "taq_up_bfq": ColumnDef("DOUBLE", nullable=True, comment="唐安奇通道(海龟)交易指标-HIGH, LOW, 20"),
            "taq_up_hfq": ColumnDef("DOUBLE", nullable=True, comment="唐安奇通道(海龟)交易指标-HIGH, LOW, 20"),
            "taq_up_qfq": ColumnDef("DOUBLE", nullable=True, comment="唐安奇通道(海龟)交易指标-HIGH, LOW, 20"),
            "trix_bfq": ColumnDef("DOUBLE", nullable=True, comment="三重指数平滑平均线-CLOSE, M1=12, M2=20"),
            "trix_hfq": ColumnDef("DOUBLE", nullable=True, comment="三重指数平滑平均线-CLOSE, M1=12, M2=20"),
            "trix_qfq": ColumnDef("DOUBLE", nullable=True, comment="三重指数平滑平均线-CLOSE, M1=12, M2=20"),
            "trma_bfq": ColumnDef("DOUBLE", nullable=True, comment="三重指数平滑平均线-CLOSE, M1=12, M2=20"),
            "trma_hfq": ColumnDef("DOUBLE", nullable=True, comment="三重指数平滑平均线-CLOSE, M1=12, M2=20"),
            "trma_qfq": ColumnDef("DOUBLE", nullable=True, comment="三重指数平滑平均线-CLOSE, M1=12, M2=20"),
            "vr_bfq": ColumnDef("DOUBLE", nullable=True, comment="VR容量比率-CLOSE, VOL, M1=26"),
            "vr_hfq": ColumnDef("DOUBLE", nullable=True, comment="VR容量比率-CLOSE, VOL, M1=26"),
            "vr_qfq": ColumnDef("DOUBLE", nullable=True, comment="VR容量比率-CLOSE, VOL, M1=26"),
            "wr_bfq": ColumnDef("DOUBLE", nullable=True, comment="W&R 威廉指标-CLOSE, HIGH, LOW, N=10, N1=6"),
            "wr_hfq": ColumnDef("DOUBLE", nullable=True, comment="W&R 威廉指标-CLOSE, HIGH, LOW, N=10, N1=6"),
            "wr_qfq": ColumnDef("DOUBLE", nullable=True, comment="W&R 威廉指标-CLOSE, HIGH, LOW, N=10, N1=6"),
            "wr1_bfq": ColumnDef("DOUBLE", nullable=True, comment="W&R 威廉指标-CLOSE, HIGH, LOW, N=10, N1=6"),
            "wr1_hfq": ColumnDef("DOUBLE", nullable=True, comment="W&R 威廉指标-CLOSE, HIGH, LOW, N=10, N1=6"),
            "wr1_qfq": ColumnDef("DOUBLE", nullable=True, comment="W&R 威廉指标-CLOSE, HIGH, LOW, N=10, N1=6"),
            "xsii_td1_bfq": ColumnDef("DOUBLE", nullable=True, comment="薛斯通道II-CLOSE, HIGH, LOW, N=102, M=7"),
            "xsii_td1_hfq": ColumnDef("DOUBLE", nullable=True, comment="薛斯通道II-CLOSE, HIGH, LOW, N=102, M=7"),
            "xsii_td1_qfq": ColumnDef("DOUBLE", nullable=True, comment="薛斯通道II-CLOSE, HIGH, LOW, N=102, M=7"),
            "xsii_td2_bfq": ColumnDef("DOUBLE", nullable=True, comment="薛斯通道II-CLOSE, HIGH, LOW, N=102, M=7"),
            "xsii_td2_hfq": ColumnDef("DOUBLE", nullable=True, comment="薛斯通道II-CLOSE, HIGH, LOW, N=102, M=7"),
            "xsii_td2_qfq": ColumnDef("DOUBLE", nullable=True, comment="薛斯通道II-CLOSE, HIGH, LOW, N=102, M=7"),
            "xsii_td3_bfq": ColumnDef("DOUBLE", nullable=True, comment="薛斯通道II-CLOSE, HIGH, LOW, N=102, M=7"),
            "xsii_td3_hfq": ColumnDef("DOUBLE", nullable=True, comment="薛斯通道II-CLOSE, HIGH, LOW, N=102, M=7"),
            "xsii_td3_qfq": ColumnDef("DOUBLE", nullable=True, comment="薛斯通道II-CLOSE, HIGH, LOW, N=102, M=7"),
            "xsii_td4_bfq": ColumnDef("DOUBLE", nullable=True, comment="薛斯通道II-CLOSE, HIGH, LOW, N=102, M=7"),
            "xsii_td4_hfq": ColumnDef("DOUBLE", nullable=True, comment="薛斯通道II-CLOSE, HIGH, LOW, N=102, M=7"),
            "xsii_td4_qfq": ColumnDef("DOUBLE", nullable=True, comment="薛斯通道II-CLOSE, HIGH, LOW, N=102, M=7"),
        },
        composite_indexes=[
            ("trade_date",),
            ("trade_date", "ts_code"),
            ("ts_code",),
        ],
    )

    def read_data(self, **kwargs: Any) -> pd.DataFrame:
        frame = self.client.call(
            "stk_factor_pro",
            fields=",".join(self.fields),
            **kwargs,
        )
        if frame is None or pd.DataFrame(frame).empty:
            return pd.DataFrame(columns=self.fields)
        return pd.DataFrame(frame).reindex(columns=self.fields)
