from shared.stock_core.config import get_env, get_int
from shared.stock_core.db import build_mysql_url


DATABASE_URL = get_env("STOCK_BI_V1_DATABASE_URL", build_mysql_url())

API_HOST = get_env("STOCK_BI_V1_API_HOST", get_env("API_HOST", "0.0.0.0"))
API_PORT = get_int("STOCK_BI_V1_API_PORT", get_int("API_PORT", 8100))

CACHE_TTL_OVERVIEW = get_int("STOCK_BI_V1_CACHE_TTL_OVERVIEW", 300)
CACHE_TTL_HEATMAP = get_int("STOCK_BI_V1_CACHE_TTL_HEATMAP", 300)
CACHE_TTL_RANKING = get_int("STOCK_BI_V1_CACHE_TTL_RANKING", 120)
CACHE_TTL_KLINE_DAILY = get_int("STOCK_BI_V1_CACHE_TTL_KLINE_DAILY", 300)
CACHE_TTL_KLINE_WEEKLY = get_int("STOCK_BI_V1_CACHE_TTL_KLINE_WEEKLY", 3600)
CACHE_TTL_SCREENER = get_int("STOCK_BI_V1_CACHE_TTL_SCREENER", 30)
CACHE_TTL_SEARCH = get_int("STOCK_BI_V1_CACHE_TTL_SEARCH", 600)

FRONTEND_DIST = get_env("STOCK_BI_V1_FRONTEND_DIST", "")

__all__ = [
    "API_HOST",
    "API_PORT",
    "CACHE_TTL_HEATMAP",
    "CACHE_TTL_KLINE_DAILY",
    "CACHE_TTL_KLINE_WEEKLY",
    "CACHE_TTL_OVERVIEW",
    "CACHE_TTL_RANKING",
    "CACHE_TTL_SCREENER",
    "CACHE_TTL_SEARCH",
    "DATABASE_URL",
    "FRONTEND_DIST",
]
